name: build-test

on: 
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop
    strategy:
      matrix:
        rosdistro:
          - humble

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Build Test
        run: |
          mkdir ../catkin_ws/src -p
          cp -r ./* ../catkin_ws/src
          cd ../catkin_ws
          rosdep install -r -y --from-paths --ignore-src ./ 
          colcon  build --symlink-install  